
# Config file for automatic testing at travis-ci.org

language: python


os:
    - linux
    - osx


before_install:
    - >
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            git clone https://github.com/lh3/bwa.git
            cd bwa
            git checkout v0.7.17
            make
            export PATH=$PATH:$(pwd)
        fi
    - >
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/blat
            chmod a+x blat
            export PATH=$PATH:$(pwd)
        fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bwa; fi
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install blat; fi


python:
  - 3.6
  - 3.5
  - 3.4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
