site_name: MAVIS

theme:
  name: "material"
repo_url: https://github.com/bcgsc/mavis
repo_name: github
site_dir: build-docs
markdown_extensions:
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
